# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Emily Oakes"
description: > # this means to ignore newlines until "email:"
  writer

email: emily@emilyoakes.com
#blog logo
logo: "/assets/images/whitepun.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/lilypic.png"

name: 'Emily Oakes'
author: 'Emily Oakes'
author_image: "/assets/images/punquin.jpg"

paginate:	5

url: "http://www.emilyoakes.com/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@Emmyoakes'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/Emmyoakes
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/authoroakes
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/loojo
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
